### ISSUE TITLE
pytorch error ?? (ImportError: No module names legacy.nn)

### ISSUE THREAD

**Issue by edwardcho** [marvis/pytorch-caffe#14]
I tested but I met error in this code.

$> python verify_deploy.py --protofile=..... --weightfile=....
----
Traceback (most recent call last):
  File "verify_deploy.py", line 3, in <module>
    from caffenet import *
  File "/home/xxxx/mll/utils/pytorch-caffe/caffenet.py", line 15, in <module>
    from torch.legacy.nn import SpatialCrossMapLRN as SpatialCrossMapLRNOld
ImportError: No module named legacy.nn
----

How to solve it??

**Comment by Animadversio** [comment]
This is a torch version problem. torch 1.0 has already deprecated this function. 

But there is a workaround, there is a new function in current pytorch [`CrossMapLRN2d`](https://github.com/pytorch/pytorch/blob/31139b5f9a0218724086cf85f5ba6554d867cddc/torch/nn/modules/normalization.py#L55) which is doing the same thing. 

So you can import this function by `from torch.nn.modules import CrossMapLRN2d` instead of `SpatialCrossMapLRNOld`

Refer to this issue https://github.com/akmtn/pytorch-siggraph2017-inpainting/issues/2

**Comment by YB17** [comment]
man, I got the same problem, thanks a lot!
