### ISSUE TITLE
How to save pytorch-model?

### ISSUE THREAD

**Issue by huangfuts** [marvis/pytorch-caffe#16]
Firstly, thanks for your significative work, which is helpful for me. But I want to save the pytorch-model, how to do that?
thanks a lot!

**Comment by DamDam123** [comment]
Hello, I would like to ask you for help. I encountered the following problem and would like to ask how you solved, Thank you!

Traceback (most recent call last):
  File "E:/Pycharm/PycharmProject/pytorch-caffe-master/usage.py", line 31, in <module>
    pytorch_blobs, pytorch_models = forward_pytorch(protofile, weightfile, image)
  File "E:/Pycharm/PycharmProject/pytorch-caffe-master/usage.py", line 20, in forward_pytorch
    net.load_weights(weightfile)
  File "E:\Pycharm\PycharmProject\pytorch-caffe-master\caffenet.py", line 638, in load_weights
    self.models[lname][1].weight.data.copy_(torch.from_numpy(np.array(lmap[lname].blobs[0].data)))
RuntimeError: The size of tensor a (2048) must match the size of tensor b (2048000) at non-singleton dimension 1
