### ISSUE TITLE
KeyError: 'group'

### ISSUE THREAD

**Issue by YenchungChen** [marvis/pytorch-caffe#2]
Hi @marvis  ,

thank you for the code.

I bump into an error while running the code "Usage" according to the README.md.

```
Traceback (most recent call last):
  File "test_Deepsaliency.py", line 37, in <module>
    pytorch_blobs, pytorch_models = forward_pytorch(protofile, weightfile, image)
  File "test_Deepsaliency.py", line 21, in forward_pytorch
    net = CaffeNet(protofile)
  File "/home/ycchen/pytorch-caffe/caffenet.py", line 381, in __init__
    self.models = self.create_network(self.net_info, width, height, channels)
  File "/home/ycchen/pytorch-caffe/caffenet.py", line 939, in create_network
    group = int(layer['convolution_param']['group'])
KeyError: 'group'
```

**Comment by rmfckaka** [comment]
I get a error too
`Traceback (most recent call last):
  File "verify_time.py", line 91, in <module>
    pytorch_time, pytorch_blobs, pytorch_models = forward_pytorch(protofile, weightfile, image, 10)
  File "verify_time.py", line 32, in forward_pytorch
    net = CaffeNet(protofile, width=args.width, height=args.height)
  File "/home/kaka/Desktop/pytorch-caffe-master/caffenet.py", line 380, in __init__
    self.net_info = parse_prototxt(protofile)
  File "/home/kaka/Desktop/pytorch-caffe-master/prototxt.py", line 62, in parse_prototxt
    if props.has_key(key):
AttributeError: 'collections.OrderedDict' object has no attribute 'has_key'
`

**Comment by Ivorra** [comment]
It seems that the error is because the attribute the log points to, does not exists in the Caffe prototxt. For example, I had to edit the code for the deconvolutional layer of `caffenet.py` by adding a check if the key existed in the dictionary, if not exists, just add the default value Caffe would give to this parameter. 

Hope it helps!
