### ISSUE TITLE
RuntimeError: inconsistent tensor size in loading caffe model

### ISSUE THREAD

**Issue by kimduckhwan** [marvis/pytorch-caffe#7]
I try to convert resnet50.prototxt, resnet50.caffemodel but I have such a error

```load weights fc1000
nn.Sequential layer weight load
Traceback (most recent call last):
  File "dump_ia_oa_w.py", line 31, in <module>
    net.load_weights(weightfile)
  File "./pytorch-caffe/caffenet.py", line 643, in load_weights
    self.models[lname][1].weight.data.copy_(torch.from_numpy(np.array(lmap[lname].blobs[0].data)))
RuntimeError: inconsistent tensor size, expected tensor [1000 x 8192] and src [2048000] to have the same number of elements, but got 8192000 and 2048000 elements respectively at /opt/pytorch/pytorch/aten/src/TH/generic/THTensorCopy.c:187```

My code is
```
import argparse
import os
import torch
import torch.nn as nn
from copy import deepcopy
import numpy as np
from caffenet import *
protofile  = '../data/ResNet50_2/ResNet-50-deploy.prototxt'
weightfile = '../data/ResNet50_2/ResNet-50-model.caffemodel'
net = CaffeNet(protofile)
net.load_weights(weightfile)
```

**Comment by blueardour** [comment]
in the weight load of the convolution and innerproduct layer:
change the original load sentence to the following:
`
caffe_weight = np.array(lmap[lname].blobs[0].data)
caffe_weight = torch.from_numpy(caffe_weight).view_as(self.models[lname].weight)
self.models[lname].weight.data.copy_(caffe_weight)
`
The main difference is the view_as

**Comment by trikim** [comment]
@blueardour 
Hello, I have the same problem. The code is already changed to what you said. But the problem can not be solved.

Error is shown as below:
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    pytorch_models = forward_pytorch(protofile, weightfile)
  File "test.py", line 4, in forward_pytorch
    net.load_weights(weightfile)
  File "/public/git/pytorch-caffe/caffenet.py", line 644, in load_weights
    self.models[lname][1].weight.data.copy_(torch.from_numpy(np.array(lmap[lname].blobs[0].data)))
RuntimeError: The expanded size of the tensor (2048) must match the existing size (2048000) at non-singleton dimension 1

**Comment by zlheos** [comment]
modify convolution blob_width computation  
[  
> add int()
 ]
@trikim @kimduckhwan 
blob_width[tname] = int((blob_width[bname] + 2*pad - kernel_size)/stride + 1)
blob_height[tname] = int((blob_height[bname] + 2*pad - kernel_size)/stride + 1)

**Comment by DamDam123** [comment]
When I run the code according to usage, I encounter the following problem

load weights bn5c_branch2c
load weights scale5c_branch2c
load weights fc1000
Traceback (most recent call last):
  File "E:/Pycharm/PycharmProject/pytorch-caffe-master/usage.py", line 31, in <module>
    pytorch_blobs, pytorch_models = forward_pytorch(protofile, weightfile, image)
  File "E:/Pycharm/PycharmProject/pytorch-caffe-master/usage.py", line 20, in forward_pytorch
    net.load_weights(weightfile)
  File "E:\Pycharm\PycharmProject\pytorch-caffe-master\caffenet.py", line 638, in load_weights
    self.models[lname][1].weight.data.copy_(torch.from_numpy(np.array(lmap[lname].blobs[0].data)))
RuntimeError: The size of tensor a (8192) must match the size of tensor b (2048000) at non-singleton dimension 1

**Comment by DamDam123** [comment]
> @blueardour
> Hello, I have the same problem. The code is already changed to what you said. But the problem can not be solved.
> 
> Error is shown as below:
> Traceback (most recent call last):
> File "test.py", line 10, in
> pytorch_models = forward_pytorch(protofile, weightfile)
> File "test.py", line 4, in forward_pytorch
> net.load_weights(weightfile)
> File "/public/git/pytorch-caffe/caffenet.py", line 644, in load_weights
> self.models[lname][1].weight.data.copy_(torch.from_numpy(np.array(lmap[lname].blobs[0].data)))
> RuntimeError: The expanded size of the tensor (2048) must match the existing size (2048000) at non-singleton dimension 1

Hello I also encountered the same problem and would like to ask how you solved it, Thanks!

**Comment by Peppa-cs** [comment]
> in the weight load of the convolution and innerproduct layer:
> change the original load sentence to the following:
> `caffe_weight = np.array(lmap[lname].blobs[0].data) caffe_weight = torch.from_numpy(caffe_weight).view_as(self.models[lname].weight) self.models[lname].weight.data.copy_(caffe_weight)`
> The main difference is the view_as

Although today is 2020.3.28, your reply still helps me!!! Thanks very much!
